services:
  app:
    build:  # 指定のDockerfileでイメージビルド(開発環境)
      context: .
      dockerfile: Dockerfile
    image: dev_container_img  # 指定のimageがあれば利用、なければこのタグで作成
    container_name: dev_container
    # ports:
    #   - "8000:8000"
    runtime: nvidia
    stdin_open: true
    tty: true

    # env_file: .env
    # environment:
      # GPG_TTY=$GPG_TTY
      # - SSH_AUTH_SOCK=/ssh-agent
      # - PATH=${PATH}:/usr/local/cuda/bin
    volumes:
      # - ${SSH_AUTH_SOCK}:/ssh-agent
      - dev_container_vol:/app
      - ~/.gitconfig:/root/.gitconfig:ro
      - ~/.gnupg:/root/.gnupg
      - ~/.git-credentials:/root/.git-credentials
      # - dev_container_gnupg_vol:/root/.gnupg
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]


volumes:
  dev_container_vol:
    external: true
  # dev_container_gnupg_vol:
  #   external: true